### ISSUE TITLE
allowed functions

### ISSUE THREAD

**Issue by eunsooan** [Webwaiter/Webwaiter#10]

**Comment by eunsooan** [comment]
## 자료정리

APUE Ch.1 UNIX System Overview
- errno(1.7)
- strerror(1.7)
\* 일반적인 에러처리 함수들

APUE Ch.3 File I/O
- close(3.5)
- read(3.7)
- write(3.8)
- dup(3.12)
- dup2(3.12)
- fcntl(3.14)
\* file I/O, redirection, file descriptor  관련 함수들

APUE Ch.4 Files and Directories
- access(4.7)
- opendir(4.22)
- readdir(4.22)
- closedir(4.22)
\* 디렉토리 관련 함수들

APUE Ch.8 Process Control
- fork(8.3)
- waitpid(8.6)
- execve(8.10)
\* Process 관련 함수들 (CGI)

APUE Ch.10 Signals
- signal(10.3)
- kill(10.9)
\* Signal 관련 함수들 (ctrl-c, ctrl-d 등 signal 처리)

APUE Ch.14 Advanced I/O
- select(14.4.1)
- poll(14.4.2)
\* Non-blocking에 대해 설명되어 있는 챕터에 소개되는 함수들 (kqueue, kevent로 대체)

APUE Ch.15 Interprocess Communication
- pipe(15.2)
\* 파이프 (CGI)

APUE Ch.16 Network IPC: Sockets
- socket(16.2)
- htonl(16.3.1)
- htons(16.3.1)
- ntohl(16.3.1)
- ntohs(16.3.1)
- getprotobyname(16.3.3)
- getaddrinfo(16.3.3)
- freeaddrinfo(16.3.3)
- gai_strerror(16.3.3)
- bind(16.3.4)
- getsockname(16.3.4)
- connect(16.4)
- listen(16.4)
- accept(16.4)
- send(16.5)
- recv(16.5)
- setsockopt(16.6)
\* 소켓 관련 함수들

https://freebsdfoundation.org/wp-content/uploads/2014/05/Kqueue-Madness.pdf
https://people.freebsd.org/~jlemon/papers/kqueue.pdf
- kqueue
- kevent
\* kqueue 관련 자료

**Comment by flowjiyun** [comment]
허용 함수 관련 구현 아이디어
1. 가상 호스팅을 구현해야 하는 것 같습니다. 
nginx conf에 적혀있는 server_name을 참고하여 어떤 docroot(서버가 참고하는 루트 디렉토리)를 참조하는지 판단할 수 있어야 될 것 같습니다. 이에 대한 판단을 할 때, 소켓 관련 함수를 사용할 수 있을지 혹은 conf 파일의 server_namer과 요청 메시지의 host 헤더 값을 비교하여 판단 하면 될지 결정이 필요합니다.

2. directory listing 과련
요청 url이 디렉토리 일경우 해야할 일은 아래와 같습니다.
- 디렉토리에 대한 기본 파일 설정 (ex. 특정 디렉토리로 요청이 올경우 찾을 파일 설정)
- 디렉토리에 기본 파일이 없고 디렉토리 리스팅 기능이 켜진 경우
디렉토리안에 있는 파일들에 대한 목록이 담겨있는 파일을 보내줘야한다.
-> 해당 기능을 구현할 때 디렉토리 관련 함수를 사용해야 할 것 같습니다.
