### ISSUE TITLE
Fix intermittent infinite loop issue on the client

### ISSUE THREAD

**Issue by flowjiyun** [Webwaiter/Webwaiter#113]
- 문제 발생 현상
    - 클라이언트 (브라우저, telnet)으로 어떤 요청을 보냈을 때 클라이언트가 응답을 받지 못하는 상황이 생김
    빙글빙글 돌면서 무한 루프, telnet 또한 응답을 받지 못함
    - 클라이언트가 응답을 받지 못한다는 것의 의미
        - 서버가 socket에 응답 메세지를 쓰지 않는다는 것(socket의 쓰기 이벤트가 켜지지 않는다는 것)
        - 쓰기 이벤트가 켜졌지만 소켓의 write 버퍼가 가득차서 kqueue가 쓰기 이벤트를 잡지 못하는 상황 가능
    - 이상한 현상
        - 응답을 받지 못했을 뿐만아니라 시간이 아무리 지나도 **커넥션이 제거되지 않는 현상이 있었음.**
        - 구현된 서버 로직상 시스템 오버로드를 시간으로서 체크하고 있기 때문에 정상적으로 시간이 체크되고 있다면 특정 시간이 지난 후 커넥션이 끊기고 디폴트 오류페이지를 보내야함
        → **시간을 업데이트하는 로직을 재점검할 필요가 있음**
        - **브라우져의 다른 탭으로 연결을 하고 요청을 보냈을 때 제대로 요청에 대한 응답이 옴**. 이러한 현상을 보았을 때 **특정 커넥션이** **워커 큐에 들어갔을 때 무한 루프에 걸린것은 아닐 것으로 추정됨.** **하나의 커넥션이 무한루프에 들어갔다면 다른 커넥션 요청또한 처리가 되지 않을 것임.**

**Comment by flowjiyun** [comment]
timeout 로직 재점검

- [ ] 파싱을 제대로 끝내지 못하였을 때, timeout에 체크로직 재점검

**Comment by kimchijinju** [comment]
Connection 클래스 내부의 state_를 초기화 하지 않아 생긴 문제로 추측됩니다.

**Comment by kimchijinju** [comment]
해결되어 이슈 닫겠습니다.
