### ISSUE TITLE
Request Message & Response Message

### ISSUE THREAD

**Issue by kimchijinju** [Webwaiter/Webwaiter#13]
## 2. 메시지 형식

```
HTTP-message   = start-line CRLF
                   *( field-line CRLF )
                   CRLF
                   [ message-body ]

Start-line     = request-line / status-line
```

메시지는 start-line으로 시작한다. 메시지는 요청일 수 있고 응답일 수 있다.

서버는 요청만, 클라이언트는 응답만 받아 처리할 수 있다. 

HTTP는 MIME(다목적 인터넷 메일 확장) 프로토콜을 사용한다.
****[https://developer.mozilla.org/ko/docs/Web/HTTP/Basics_of_HTTP/MIME_types](https://developer.mozilla.org/ko/docs/Web/HTTP/Basics_of_HTTP/MIME_types)

### 구문 분석

1. start-line을 구조체로 읽는다.
2. 다음 CRLF까지 각 헤더 필드 줄을 해시 테이블로 저장한다.
3. 2의 데이터를 사용해 메시지 본문이 있는지 확인한다.
4. 본문이 있다면 (Content-length) 메시지 본문 길이와 동일한 양의 옥텟이 읽히거나 연결이 닫힐 때 까지 스트림으로 읽는다.

수신자는 반드시 메시지를 옥텟 시퀀스(8비트 덩어리)로 구문을 분석해야한다. 그렇지 않으면 보안 취약성이 발생한다.

메시지를 추출하고 나서는 문자열 기반 구문 분석을 해도 된다.

Start-line 및 field의 종결 문자는 CRLF지만 수신자는 단일 LF을 종결 문자로 인식할 수 있다. (앞의 CR을 무시할 수 있다 (?))

발신자는 bare CR(LF가 바로 뒤에 오지 않는 CR문자)을 생성해서는 안된다. bare CR을 수신했다면 수신자는 유효하지 않게 처리하거나,  space로 변환해서 처리해야 한다.

Start-line을 수신하고 header line이 수신되기 전 서버는 수신된 CRLF을 하나 이상 무시해야 한다. (견고성을 위해)

발신자는 Start-line을 수신하고 첫 번째 header를 보내기 전 white space을 보내면 안된다.
Start-line을 수신하고 첫 번째 header를 보내기 전 white space를 수신하면 수신자는 메시지를 유효하지 않은 것으로 거부하거나 처리하지 않고 소비해야한다. 요청 스머핑, 응답 분할 공격에 취약할 수 있기 때문이다.

견고성을 위한 예외를 제외하고, 서버는 메시지 문법과 맞지 않으면 400을 응답하고 연결을 닫아야한다.

### HTTP Version

버전은 Start-line Http version field에 표시된다.

```
  HTTP-version  = HTTP-name "/" DIGIT "." DIGIT
  HTTP-name     = %s"HTTP"
```

서버는 클라이언트가 보낸 요청에서 버전 구문 분석에 실패한다면 HTTP 1.1 요청에 HTTP 1.0 응답을 보낼 수 있다.

## Request Line

```
  request-line   = method SP request-target SP HTTP-version
```

단일 space로 구분되어야 하지만, 모든 형태의 space(SP, HTAB, VT (%x0B), FF (%x0C), or bare CR)로도 구분되게 구현해도 된다. 그러나 구문 분석이 관대하면 보안 취약점이 생길 수 있다.

서버가 구현하지 않은 Method를 수신하면 501(Not Implement) 상태 코드를 응답해야 한다.

너무 긴 URI를 수신하면 414(URI Too Long) 상태 코드를 응답해야한다. << HTTP 15.5.15

Request Line은 최소 8000 octet 길이를 지원하는 것을 권장한다.

### Request Target

Request Target은 요청을 적용할 대상 자원을 식별한다. Request Target에는 네 가지 형식이 있다.

```
  request-target = origin-form
                 / absolute-form
                 / authority-form
                 / asterisk-form
```

Request Target에는 공백이 허용되지 않으나, 일부 사용자 프로그램은 공백이나 허용되지 않은 문자를 제외하지 못한 채 요청을 보낸다.

이 경우 잘못된 Request Line을 받은 수신자는 400(Bad Request) 오류 또는 301(Moved Permanently) 리디렉션으로 응답해야 한다. 보안 필드를 우회하기 위해 의도적으로 작성되었을 수 있으므로 수신자는 리디렉션 없이 처리해서는 안된다.

클라이언트는 모든 Request Message에 Host header 필드를 넣어야 한다. 대상 URI에 권한 구성 요소가 포함된 경우 사용자 정보 하위 구성 요소와 @ 구분 기호를 제외하고 해당 권한 구성요소와 동일한 Host 필드 값으로 전송해야 한다.

서버는 요청에 Host 필드가 없거나 두 개 이상이라면 400(Bad Request)을 응답한다.

### origin-form

```
  origin-form    = absolute-path [ "?" query ]

ex)
http://www.example.org/where?q=now 이 형식으로 데이터를 보낸다면

GET /where?q=now HTTP/1.1
Host: www.example.org
헤더는 이렇게 만들어진다.
```

### absolute-form

```
  absolute-form  = absolute-URI

ex)
GET http://www.example.org/pub/WWW/TheProject.html HTTP/1.1
```

서버는 이 형식의 요청을 수신하면 Host 헤더 필드가 있더라도 무시하고, absolute-form에 있는 호스트 정보를 사용해야 한다. 그러나 absolute-form에 권한 구성요소가 없는 경우, 빈 Host 헤더 필드가 전송된다.
대부분의 HTTP/1.1 클라이언트가 absolute-form을 프록시에게만 전송하더라도, 서버는 요청에서 absolute-form을 허용해야 한다.

GPT에게 물어보니 서버가 여러 포트에서 호스팅하는 경우에 이걸 사용해서 요청을 처리할 수 있다고 하네요.

### authority-form, asterisk-form

authority-form은 CONNECT 요청에만 사용된다. 
프록시 서버같은 중개자가 사용한다고 하고, 일반적인 웹서버는 구현하지 않는다고 합니다.

asterisk-form은 OPTIONS 요청에만 사용된다.
asterisk-form도 마찬가지로 일반적인 웹서버에서는 구현할 필요는 없다고 하네요.

### ****Reconstructing the Target URI****

Request-target이 absolute-form인 경우, URI를 파싱해야한다.

absolute-form 안에 있는 정보를 파싱해서 response 헤더를 만들어야 한다는 내용같은데, 이해하기 쉽지 않아서 내일 다시 정리해보겠습니다.

### 4. Status Line

```
status-line = HTTP-version SP status-code SP [ reason-phrase ]

status-code = 3DIGIT
```

Request Line과 똑같이 SP로 구분되어야 한다.

**status-code**는 3자리 정수다.

**reason-phrase**는 상태 코드에 관련된 텍스트 설명을 제공하는데, 정보를 전달하는 목적으로 사용하는 부분이 아니어서 클라이언트는 이 내용을 무시해야 한다.

### 5. Field Syntax

```
field-line   = field-name ":" OWS field-value OWS 
(OWS = optional whitespace)
```

콜론 사이에 공백은 선택적이다.

### Field value

```
field-value    = *field-content
field-content  = field-vchar
                 [ 1*( SP / HTAB / field-vchar ) field-vchar ]
field-vchar    = VCHAR / obs-text
obs-text       = %x80-FF

Singleton 멤버에도 쉼표가 들어갈 수 있으니 잘 구분해 파싱해야한다.
Example-URIs: "http://example.com/a.html,foo",
              "http://without-a-comma.example.com/"
Example-Dates: "Sat, 04 May 1996", "Wed, 14 Sep 2005"
#element => [ element ] *( OWS "," OWS [ element ] )

```

- 공백이 포함되지 않는다.
- USASCII문자만 사용 가능하다. 다른 인코딩을 사용하려면 RFC8187에 정의된 인코딩 사용가능
- CR, LF, NULL 문자가 포함된 필드는 거부하거나 SP로 대체한다.
- 많은 필드(ex: content-type)는 token과 quoted-string을 모두 허용한다.
    - token → 
    "!" / "#" / "$" / "%" / "&" / "'" / "*"
    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
    / DIGIT / ALPHA; delimiters을 제외한 모든 VCHAR가 올 수 있다.
    - quoted-string →
    
    ```
    quoted-string  = DQUOTE *( qdtext / quoted-pair ) DQUOTE
    qdtext         = HTAB / SP / %x21 / %x23-5B / %x5D-7E / obs-text
    백슬래쉬(\)을 이용하여 escape 문자를 처리할 수 있다.
    ```
    
- field value에 단일 멤버만 존재하면 **singleton fields**라 한다.
- field value에 여러 멤버가 존재하면 **list-based fields**라 한다.
    - 쉼표(,)가 구분 기호로 사용된다.
    - 싱글톤 멤버에도 쉼표가 들어갈 수 있으니 잘 구분해서 파싱해야한다.
    - [ element ] OWS "," OWS [ element ] 형태로 입력된다. element가 비어있을 가능성이 있다. 비어있는 부분은 무시한다.
- Comment (주석?)
    - 허용하는 Field에 한해 텍스트를 괄호로 감싸 Comment를 포함할 수 있다. →
    
    ```
    comment        = "(" *( ctext / quoted-pair / comment ) ")"
    ctext          = HTAB / SP / %x21-27 / %x2A-5B / %x5D-7E / obs-text
    ```
    
- Parameter
    - 이름/값 쌍의 인스턴스다. Field value에 자주 사용된다.
    - 각 argument 앞에 ;로 구분한다. →
    
    ```
    parameters      = *( OWS ";" OWS [ parameter ] )
    parameter       = parameter-name "=" parameter-value 사이에 공백을 허용하지 않음
    parameter-name  = token  대소문자 구분 하지 않음
    parameter-value = ( token / quoted-string ) 매개변수의 의미에 따라 대소문자 구분ㄴ
    ```
    
- 날짜
    
    ```
    HTTP-date    = IMF-fixdate / obs-date
    
    기본 형식
    Sun, 06 Nov 1994 08:49:37 GMT    ; IMF-fixdate
    
    더이상 사용되지 않는 형식
    Sunday, 06-Nov-94 08:49:37 GMT   ; obsolete RFC 850 
    Sun Nov  6 08:49:37 1994         ; ANSI C's asctime() format
    
    IMF-fixdate에 대해 더 자세한 문법은 RFC9110/5.6.7 
    ```
    
    - 수신자는 세 가지 형식 모두 파싱할 수 있어야한다.
    - UTC의 인스턴스로 시간을 나타낸다.
    - UTC 시간을 구할 수 있도록 구현하기 위해, NTP 또는 유사한 프로토콜을 사용해야 한다.
    - 대소문자를 구분해야 한다.
    - 타임스탬프를 강력하게 파싱하는 것을 권장한다.
    - 문법에서 허용하는 공백을 제외하고, 추가 공백을 생성하면 안된다.

### Field line parsing

field name과 : 사이에는 공백이 허용되지 않는다. 과거에 보안 취약점이 발생해서.. 공백이 들어왔다면 400(Bad Request)를 응답한다.

space는 값을 추출할 때 제외하면 된다.

### ****Obsolete Line Folding****

과거에는 다음과 같이 필드 값이 여러 줄에 걸쳐 작성될 수 있었다.

```
obs-fold     = OWS CRLF RWS
               ; obsolete line folding
```

HTTP 1.1에서는 message/http 유형을 제외하고는 obs-fold는 사용되지 않는다.

message/http에 속하지 않는 obs-fold를 수신했다면 400(Bad Request)로 거부하거나 obs-fold를 sp 옥텟으로 대체해야 한다.

**Comment by flowjiyun** [comment]
1. 메세지 파싱 관련 도움
    - 시작 줄과 헤더의 끝은 캐리지리턴(13번) 개행 문자(10번)으로 끝이나며 아스키 문자열이다
    - 헤더의 집합은 항상 빈줄 (CRLF)로 끝이나야 한다.
    - 본문은 있을 수도 있고 없을 수도 있으며 텍스트 일수도 있고 이진 데이터 일 수도 있다.
    - 헤더
        - 이름, 콜론(:), 선택적인공백(없어도됨), 값, CRLF 로 한줄이 구성됨.
        - 한줄의 헤더를 여러 줄로 나눠서 표현할 수 있음
            - 추가 줄 앞에 최소 하나의 스페이스 혹은 탭 문자가 와야 함
        
        ```cpp
        server: test server
        	version 1.0
        ```
        
    - 요청줄, 응답줄
        - 각 필드는 공백으로 구분된다

**Comment by kimchijinju** [comment]
```
Recipients of an invalid request-line SHOULD respond with either a 400 (Bad Request) error or a 301 (Moved Permanently) redirect with the request-target properly encoded. A recipient SHOULD NOT attempt to autocorrect and then process the request without a redirect, since the invalid request-line might be deliberately crafted to bypass security filters along the request chain.
```

```
Older HTTP/1.0 user agent implementations might send an extra CRLF after a POST request as a workaround for some early server applications that failed to read message body content that was not terminated by a line-ending. An HTTP/1.1 user agent MUST NOT preface or follow a request with an extra CRLF. If terminating the request message body with a line-ending is desired, then the user agent MUST count the terminating CRLF octets as part of the message body length.
```

이 두 부분이 해석이 잘 안되네요 ㅜ 

내일은 HTTP Version 부분 내용 채우고, 3~5장 더 공부해보겠습니다.

**Comment by eunsooan** [comment]
### 길이 제한 관련
> At a minimum, a recipient MUST be able to parse and process protocol element lengths that are at least as long as the values that it generates for those same protocol elements in other messages. For example, an origin server that publishes very long URI references to its own resources needs to be able to parse and process those same references when received as a target URI. -- _RFC 9110 2.3 Length Requirements_

서버는 적어도 자기가 만들어내는 메세지 구성요소의 길이 만큼은 받아서 파싱하고 처리할 수 있어야 한다.

**Comment by eunsooan** [comment]
### 메세지 처리 방식
> Messages are expected to be processed as a stream, wherein the purpose of that stream and its continued processing is revealed while being read. Hence, control data describes what the recipient needs to know immediately, header fields describe what needs to be known before receiving content, the content (when present) presumably contains what the recipient wants or needs to fulfill the message semantics, and trailer fields provide optional metadata that was unknown prior to sending the content. -- _RFC 9110 6 Message Abstraction_

메세지는 읽혀지면서 동시에 처리된 내용이 밝혀지도록 stream으로서 처리된다. 따라서, 수신자가 즉시 알아야하는 것을 control data(시작줄을 의미하는 것 같음)가 설명하고, 내용을 받기 전에 알아야 할 것을 header field들이 설명한다.

**Comment by kimchijinju** [comment]
내일은 Reconstructing the Target URI, field-value 파싱 규칙을 작성하고 5~8장 작성해보겠습니다.

**Comment by eunsooan** [comment]
### Date Header Field
> An origin server with a clock (as defined in [Section 5.6.7](https://www.rfc-editor.org/rfc/rfc9110.html#http.date)) MUST generate a Date header field in all [2xx (Successful)](https://www.rfc-editor.org/rfc/rfc9110.html#status.2xx), [3xx (Redirection)](https://www.rfc-editor.org/rfc/rfc9110.html#status.3xx), and [4xx (Client Error)](https://www.rfc-editor.org/rfc/rfc9110.html#status.4xx) responses, and MAY generate a Date header field in [1xx (Informational)](https://www.rfc-editor.org/rfc/rfc9110.html#status.1xx) and [5xx (Server Error)](https://www.rfc-editor.org/rfc/rfc9110.html#status.5xx) responses. -- _RFC 9110 6.6.1 Date_

클락 기능이 있는 오리진 서버는 모든 2xx, 3xx, 4xx 응답에 date header를 넣어야한다.

**Comment by flowjiyun** [comment]
## 응답 메세지

- 응답 본문을 생성한다면 아래의 헤더를 포함해야한다.
    - 응답 본문의 MIME 타입을 서술하는 Content-type 헤더
    - 응답 본문의 길이를 서술하는 Content-Length 헤더
    - 실제 응답의 본문
- MIME 타입 결정하는 방법
    - 파일 이름의 확장자를 참고 하는 방법 (가장 흔한 방식)
        - 확장자별 MIME 타입에 대한 내용이 담겨있는 파일을 탐색하여 결정
    - 매직 타이핑
        - 파일 내용을 검사하여 알려진 패턴이 있는지 찾아서 표준 확장자가 없는 파일에 대해서도 타입을 알아낼 수 있다.
    - 유형 명시
        - 특정 파일 혹은 특정 디렉토리에 특정 MIME 타입을 갖도록 서버 자체를 설정할 수 있음
- 리다이렉트 응답 메세지
    - 요청을 수행하기위해 브라우저가 다른 곳을 참고하도록 하는 것을 리다이렉트라고 한다.
    - 상태코드는 3xx 이며 Location 응답 헤더는 리소스의 새로운 위치를 url로 알려준다
    - 사용되는 경우
        - 리소스가 옮겨진 경우
        - URL 증강
            - 서버는 상태 정보를 포함한 URL(fat url)을 작성하여 리다이렉트 응답을 보낸다
            - 이를 통해 트랜젝션간 상태를 유지할 수 있다.
        - 부하 균형
            - 서버에 부하가 걸리면 다른 서버로 리다이렉트
        - 친밀한 다른 서버가 있을 때
            - 웹 서버는 어떤 사용자에 대한 정보를 가질 수가 있는데 해당 서버로 리다이렉트 할 수 있다.

**Comment by eunsooan** [comment]
### Content-Type Header Requirement
> A sender that generates a message containing content SHOULD generate a Content-Type header field in that message unless the intended media type of the enclosed representation is unknown to the sender. If a Content-Type header field is not present, the recipient MAY either assume a media type of "application/octet-stream" ([[RFC2046](https://www.rfc-editor.org/rfc/rfc9110.html#RFC2046)], [Section 4.5.1](https://www.rfc-editor.org/rfc/rfc2046#section-4.5.1)) or examine the data to determine its type.-- [RFC 9110 8.3 Content-Type](https://www.rfc-editor.org/rfc/rfc9110.html#section-8.3-5)

본문이 포함된 메세지를 전송하는 송신자는 (송신자가 동봉된 representation의 의도된 media type을 모를 때를 제외하고)* Content-Type 헤더를 추가해야한다.

\* 이런 상황이 저희한테 있을진 아직 모르겠네요

**Comment by eunsooan** [comment]
### 대문자로 강조된 키워드(예: MUST, SHOULD)에 대한 설명 RFC
[Key words for use in RFCs to Indicate Requirement Levels](https://www.rfc-editor.org/rfc/rfc2119)
짧으니까 한번씩 훑어보세요~

**Comment by eunsooan** [comment]
### 1xx와 204 응답코드
> A server MUST NOT send a Content-Length header field in any response with a status code of [1xx (Informational)](https://www.rfc-editor.org/rfc/rfc9110.html#status.1xx) or [204 (No Content)](https://www.rfc-editor.org/rfc/rfc9110.html#status.204). -- _[RFC 9110 8.6 Content-Length](https://www.rfc-editor.org/rfc/rfc9110.html#section-8.6-8)_

서버는 1xx(정보 제공)와 204(본문 없음) 응답코드에 Content-Length header를 달면 안된다.

**Comment by eunsooan** [comment]
### Body
> The last part of a response is the body. Not all responses have one: responses with a status code that sufficiently answers the request without the need for corresponding payload (like [201](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201) Created or [204](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) No Content) usually don't.
> 
> Bodies can be broadly divided into three categories:
> 
> * Single-resource bodies, consisting of a single file of known length, defined by the two headers: [Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) and [Content-Length](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length).
> * Single-resource bodies, consisting of a single file of unknown length, encoded by chunks with [Transfer-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding) set to chunked.
> * [Multiple-resource bodies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#multipartform-data), consisting of a multipart body, each containing a different section of information. These are relatively rare.
> 
> -- _[MDN Web Docs HTTP Messages](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages#body_2)_

메세지 Body, 즉 Content의 길이를 모를 때 Transfer-Encoding: chucked 헤더를 이용해 나눠 보낼 수 있습니다. (Request message 메소드가 POST일 때도 가능할 것 같습니다.)

**Comment by flowjiyun** [comment]
## Transfer Encoding

transfer encoding의 종류로 청크 인코딩이 있다.

- 관련  헤더
    - transfer encoding
        - 어떤 인코딩이 메세지에 적용되었는지 알려줌
    - TE
        - 어떤 인코딩을 사용할 수 있는지 수진자에게 자신의 능력 범위를 알려줌
    
    ```cpp
    GET /index.html HTTP/1.1
    Host: www.example.com
    TE: trailer, chunked
    
    HTTP/1.1 200 OK
    Transfer-Encoding: chunked
    ```
    

HTTP/1.1은 청크 인코딩만 명세에 정의하고 있으며 해당 헤더의 값은 대소문자를 구별한다.

## Chunk Encoding

- 메시지를 일정 크기의 청크 여럿으로 쪼개어 보내는 방법.
- 본문이 동적으로 생성되는 경우 사용함. 본문의 전체크기를 알 수 없을 때.
- 지속 커넥션에서의 청크 인코딩
    - 청크를 크기와 함께 보내고 전체 본문을 보낼때 까지 반복한다.
    - 본문을 모두 보냈을 경우 마지막으로는 크기가 0인 청크를 보냄으로서 마지막임을 알린다.
    - 청크의 형식
        - 길이는 16진수값으로 마지막에 CRLF로 구분
        - 길이 이후에는 해당 길이 만큼의 내용을 담고 CRLF로 구분
        - 단, 길이에는 CRLF 값은 포함되지 않음
![Untitled](https://github.com/Webwaiter/Webwaiter/assets/99542049/e2c18dea-8264-45d5-8470-2831e8c16083)
