### ISSUE TITLE
Connection Management

### ISSUE THREAD

**Issue by eunsooan** [Webwaiter/Webwaiter#15]

**Comment by flowjiyun** [comment]
HTTP 완벽가이드 1부 4장에 커넥션 관리에 대해서 다루고 있더라고요. RFC 읽기 전에 해당 부분 읽으면 이해하는데 도움이 될거 같습니다!

**Comment by flowjiyun** [comment]
tcp/ip 커넥션은 아래의 네가지 값으로 유일한 커넥션을 식별할 수 있다

- 발신지 ip, 수신지 ip, 발신지 포트, 수신지 포트

## TCP 소켓 프로그래밍

운영체제는  TCP 커넥션 생성과 관련된 여러기능을 사용자에게 제공한다. 소켓 api는 HTTP 프로그래머에게  TCP/IP의 세부사항을 숨긴다. 핸드세이킹 과정, 데이터스트림 분할및 조립에 대한 모든 세부사항을 외부에 숨긴다.

## TCP성능에 대한 고려

HTTP 트랜젝션 지연의 원인은 대부분 TCP 네트워크 지연때문에 발생

1. dns 를 통한 ip 주소 찾기 (캐싱되어 있으면 빨리 찾는다)
2. 커넥션 설정 시간 새로운 TCP 커넥션에서 항상 발생한다
3. 클라이언트가 요청을 보내고 서버까지 가는데 걸리는 시간
4. 서버가 처리한 응답이 클라이언트까지 가는 시간

→ TCP 지연은 하드웨어 성능, 네트워크와 서버의 전송 속도, 요청과 응답 메시지의 크기, 클라이언트와 서버간의 거리에 따라 달라진다.

- 성능 관련 중요 요소
    - TCP 커넥션의 핸드세이크 설정
    
    해당 과정에서 HTTP 프로그래머가 보는 것은 새로운 TCP 커넥션이 생성될 때 발생하는 지연이 전부임
    
    HTTP 트랜젝션이 큰 데이터를 주고 받는 경우가 아니라면 해당 핸드세이크 부분이 차지하는 지연이 크다
    
    크기가 작은 HTTP트랜잭션은 50% 이상의 시간을 TCP를 구성하는데 쓰임.
    
    이러한 지연 제거를 위해 이미 존재하는 커넥션을 재활용할 수 있음.
    
    - 인터넷 혼잡을 제어하기 위한 TCP의 느린 시작(slow start)
        - 커넥션이 갓 만들어 졌을 때는 보낼수 있는 패킷을 양이 적지만 시간이 지날수로 늘어나게된다.
        - 인터넷의 급작스러운 부하와 혼잡을 방지하는데 쓰인다.
        - 이러한 혼잡 제어로 인해 새로운 커넥션은 시간이 지나 튜닝된 커넥션보다 느리다
        - HTTP에는 이미 존재하는 커넥션을 재사용하는 기능이 있음
    - 데이터를 한데 모아 한번에 전송하는 네이글 알고리즘
        - 세그먼트가 최대 크기가 되지 않으면 전송을 하지 않는다
        - 크기가 작은 HTTP 메세지는 패킷을 최대 크기를 채우지 못하기 때문에 앞으로 생길지 생기지 않을지 모르는 추가적인 데이터를 기다리면 지연될 수 있다.
        - 확인 응답이 도착할 때까지 데이터 전송을 멈추고 있기 때문에 확인 응답 지연 알고리즘과 같이 사용하면 더 안좋은 성능을 보인다
        - 네이글 알고리즘을 비활성화 시킬수 있다 TCP_NODELAY파라미터값 지정하여
    - TCP의 편승(piggyback) 확인응답(acknowledgment)을 위한 확인 응답 지연 알고리즘
        - 송출 데이터 패킷에 확인응답을 하나 묶여 편승 시킴으로서 네트워크를 효율적으로 사용하려고 한다.
        - 확인 응답이 편승되는 경우를 늘리기 위해 확인 응답 지연 알고리즘을 사용한다.
        - 송출할 확인응답을 0.1~0.2초 동안 버퍼에 저장해 두고 확인 응답을 편승시킬 송출 데이터 패킷을 찾는다.
        - 일정 시간동안 편승 패킷을 찾지 못하면 별도의 패킷을 만들어서 전송된다.
    - TIME_WAIT 지연과 포트 고갈
        - TCP 커넥션을 끊었을 때 IP 주소와 포트를 control block에 잠시 기록해 놓는다
        - 같은 포트와 아이피 번호를 사용하는 tcp 커넥션이 최대 생명주기의 2배인 약 2분동안 생성되지 않도록 하기 위함이다.
        - 이유는 같은 커넥션이 생겼을 때 이전 커넥션에서 생긴 패킷이 새로운 커넥션에 삽입 될 수 있기 때문이다.
        - 현대의 빠른 라우터들 덕분에 커넥션이 닫힌 후에 중복되는 패킷이 생기는 경우는 거의 없어 졌다

## HTTP 커넥션 관리

- Connection 헤더
    - hope by hope 특성을 가지고 있어 특정 두 서버 간에만 영향을 미치고 다른 서버간에는 여향을 미치지 않는다
- HTTP 커넥션 성능 향상을 위한 기술
    1. 병렬 커넥션
        - 여러개의 TCP 커넥션을 통한 동시 요청
        - 클라이언트가 각각 다른 포트 번호를 통해 서버와 여러개의 연결을 맺는다
        - 보통 6~8개 까지
    2. 지속 커넥션
        - 커넥션을 맺고 끊는 데서 발생하는 지연을 제거하기 위한 TCP 커넥션의 재활용
        - HTTP1.1을 지원하는 기기는 처리가 완료된 후에도 TCP커넥션을 유지하여 앞으로 있을 HTTP요청에 재사용 할 수 있다.
        - 클라이언트나 서버가 커넥션을 끊기 전까지 유지
        - 커넥션을 맺기 위한 준비작업 시간을 절약하고 느린 시작으로 인한 지연을 피할 수 있음
        - 종류
            - HTTP 1.0+의 keep alive
                - 커넥션 유지를 위해 요청 헤더에 connection: Keep-Alive 헤더를 포함시킴
                - 서버가 이휴 요청도 커넥션을 유지하고 싶다면 동일 헤더를 명시해서 보냄
                - keep-alive 헤더가 없으면 클라이언트는 서버가 응답을 보낸뒤 커넥션을 끊을 것으로 추정함
                - 해당 요청은 바람일 뿐 무조건 따를 필요는 없다
            - HTTP 1.1의 지속 커넥션
                - 지속 커넥션이 기본으로 활성화 되어 있음
                - 별도의 설정을 하지 않는 한 모든 커넥션을 지속 커넥션으로 취급함
                - 커넥션을 끊고 싶다면 connection: close 헤더를 명시해야함
                - 하지만 클라이언트와 서버는 언제든 커넥션을 끊을 수 있음. connection: close를 보내지 않는 다고 해서 서버가 커넥션을 영원히 유지하겠다느 것은 아님
                - 제한과 규칙
                    - 클라이언트가 해당 커넥션으로 더이상 요청을 보내지 않을 것이라면 마지막 요청에 connection: close 헤더를 보내야 함.
                    - 커넥션에 있는 모든 메시지의 길이 정보가 정확해야만 커넥션을 지속할 수 있다. content-length가 정확한 값이어야함
    3. 파이프라인 커넥션
        - 공유 TCP 커넥션을 통한 병렬 HTTP 요청
        - 규칙
            - 클라인트는 지속 커넥션임을 확인지 전까지 파이프라인을 이어서는 안된다
            - 응답 메세지는 요청 메세지 순서와 같에 와야한다.
            - 커넥션이 언제 끊어지더라도 파이프라인에 요청이 있으면 언제든 다시 보낼 수 있어야 한다.
            - POST 요청과 같이 다시 요청을 보냈을 때 문제가 생기는 요청은 파이프라인을 통해 보내면 안된다.

## HTTP 커넥션 끊기

- 커넥션 관리에는 명확한 기준이 없다 HTTP 명세에도 커넥션 끊기에 대한 명확한 규칙이 적혀 있지 않다.
- 어떠한 HTTP 어플리케이션이든 원할 때 커넥션을 끊을 수 있다. 보통의 경우 메세지를 다 보낸 후 끊지만, 에러 상황의 경우 중간에 끊길 수도 있다.
- 커넥션 ‘절반’ 끊기(shutdown() 함수)
    - 보통 서버는 안전하게 커넥션의 출력만 먼저 끊는다(권장사항, 명세에 적혀있지 않음)
    - 만약 서버의 입력을 끊고 클라이언트가 요청 메세지를 보낸다면 운영체제는 ‘connection reset by peer’ 오류를 클라이언트에 보낼 것이다. 이것을 클라이언트 운영체제는 심각한 오류로 판단하여 클라이언트 소켓 입력 버퍼에서 아직 읽히지 않은 모든 데이터를 지운다.  결론적으로 클라이언트에 제대로 도착하였지만 아직 읽지못해 버퍼에 있는 응답데이터가 모두 사라지게된다.

**Comment by eunsooan** [comment]
# 9. 연결 관리
HTTP 메세징은 하위 전송 계층 또는 세션 계층 프로토콜과 독립되어있다. HTTP는 요청과 그에 대한 응답을 순서에 맞게 전달하는 신뢰적 데이터 전송만을 가정한다. HTTP 요청과 응답 구조와 하위 전송 계층 프로토콜 데이터 단위의 대응관계는 이 명세서의 범위 밖이다.

HTTP 상호작용에 사용되는 구체적인 연결 프로토콜은 클라이언트 설정과 타겟 URI로 결정된다. 예를 들어 "http" URI 스킴은 기본적으로 80번 TCP 포트번호를 사용하는 TCP/IP 연결을 가르키지만 프록시를 통해 다른 연결방식이나 포트, 프로토콜을 사용하여 HTTP 상호작용을 하도록 클라이언트를 설정할 수 있다.

HTTP 구현체는 **연결 관리(현재 구성된 연결들의 연결 상태 관리, 새 연결 구성 또는 이미 구성되어있는 연결 재사용, 연결로 받은 메세지 처리, 연결 실패 감지, 연결 해제)** 를 하도록 요구된다. 대부분의 클라이언트는 서버당 두 개 이상의 연결을 포함하는 다수의 연결을 병렬로 유지한다. 대부분의 서버는 DOS 공격 감지와 각 연결에 공정한 서비스를 위해 요청큐를 사용하며 수천개의 연결을 동시에 유지하도록 설계되어있다.

## 9.1 연결 구성
연결이 어떻게 다양한 전송 계층 혹은 세션 계층을 통해 구성되는지에 대한 설명은 이 명세서의 범위 밖이다. 각 HTTP 연결은 하나의 하위 전송 계층을 사용한다.

## 9.2 요청과 응답 짝 맞추기
HTTP/1.1은 주어진 요청 메세지와 이에 대응하는 하나 혹은 다수의 응답 메세지를 짝 맞출 때 사용할 수 있는 요청 식별자를 추가하지 않는다. 따라서 HTTP/1.1은 각 연결로 보낸 요청 메세지들을 올바르게 짝 맞추기 위해 응답의 도착 순서에 의존한다. **한 요청 메세지에 대해 다수의 응답 메세지가 발생하는 경우는 하나 이상의 1xx 응답코드를 가진 정보성 응답이 최후 응답에 앞서 전달될 때 밖에 없다.**

아직 처리되지 않은 요청을 두 개 이상 가진 클라이언트는 처리되지 않은 요청에 대한 리스트를 만들어 보낸 순서를 관리해야하며 응답 메세지를 받으면 처리되지 않은 요청들 중 최후(1xx가 아닌)응답을 받지 않은 첫 요청과 짝지어야한다. 

만약 클라이언트가 처리되지 않은 요청이 없는 연결로부터 데이터를 받으면 클라이언트는 그 데이터를 유효한 응답으로 보지 않아야한다. 데이터에 하나 이상의 CRLF만 들어있는 경우가 아니면 메세지의 분계가 모호해지는 상황이 발생되기 때문에 클라이언트는 해당 연결을 닫는 것이 권장된다.

## 9.3 지속성
HTTP/1.1은 기본적으로 "지속 연결"을 사용하여 다수의 요청과 응답이 한 번의 연결로 오갈 수 있도록 한다. HTTP 구현체는 지속 연결을 지원하도록 권장된다.

메세지 수신자는 연결의 지속성 여부를 가장 최근에 받은 메세지의 프로토콜 버젼과 Connection 헤더를 통해 판단한다.
- **IF "close" connection 옵션이 있다면 해당 요청의 응답 후 연결은 지속되지 않는다. ELSE**
- **IF 받은 메세지의 프로토콜이 HTTP/1.1 혹은 그 이후 버젼이라면 해당 요청의 응답 후에도 연결은 지속된다.** ELSE
- IF 받은 메세지의 프로토콜이 HTTP/1.0이고, "keep-alive" connection 옵션이 있고, 수신자가 프록시가 아니거나 메세지가 응답이고, 수신자가 HTTP/1.0 "keep-alive" 메커니즘을 지키고 싶다면 당 요청의 응답 후에도 연결은 지속된다. OTHERWISE
- 해당 요청의 응답 후 연결은 지속되지 않는다.

지속 연결을 지원하지 않는 클라이언트는 모든 요청 메세지에 "close" connection 옵션을 붙여야한다.

지속 연결을 지원하지 않는 서버는 1xx(정보) 응답 코드를 갖고 있지 않은 모든 응답 메세지에 "close" connection 옵션을 붙여야한다.

클라이언트는 "close" connection 옵션 메세지를 보내거나 받기 전, 혹은 "keep-alive" connection 옵션이 없는 HTTP/1.0 응답을 받기 전까지 지속 연결에 추가 요청을 보낼 수 있다.

**지속성을 유지하기 위해 모든 메세지는 스스로 정의한(연결 해제를 통해 간접적으로 정의되지 않은) 메세지 길이를 포함하고 있어야한다. 서버는 요청 메세지 전체를 읽어들이거나, 응답을 보낸 후 연결을 닫아야한다. 그렇지 않으면 지속 연결에 남아있는 데이터가 다음 요청으로 잘못 해석될 수 있기 때문이다.** 마찬가지로 클라이언트는 해당 연결을 차후 요청을 보낼 때 재사용하려면 응답 메세지 전체를 읽어들여야한다.

### 9.3.1 요청 재시도 (건너뜀)
### 9.3.2 파이프라이닝 (건너뜀)
## 9.4 병행성 (건너뜀)
## 9.5 실패와 타임아웃
내일 계속
## 9.6 해제
내일 계속

**Comment by flowjiyun** [comment]
언제 서버에서 커넥션을 끊을 수 있을까?
- 클라이언트에서 끊었을 경우 EV_EOF 비트를 확인하여 끊을 수 있다.
- 서버 입장에서 에러가 발생했을 때 일방적으로 끊는다
- timeout을 구현한다면 timeout 발생시 끊는다
