### ISSUE TITLE
Runtime and semantic errors

### ISSUE THREAD

**Issue by eunsooan** [Webwaiter/Webwaiter#63]
- [x] 프로그램 인자로 디렉토리를 넣을 경우 abort 발생
- [x] 프로그램 인자가 없을 때 default path로 찾아가야 함
- [ ] telnet으로 요청을 보내면 응답이 오지 않음
- [x] 동일 클라이언트가 연결 시도를 여러번 했을 때 segmentation fault 발생
- [x] I/O 작업이 필요없는데 work() 함수에서 나가서 kevent에서 대기
- [x] timeout 확인하지 않음
- [x] connection clear함수 만들기

**Comment by flowjiyun** [comment]
아래 이슈들 별도 브랜치로 해결 후 PR 하겠습니다.
- [ ] 프로그램 인자로 디렉토리를 넣을 경우 abort 발생
- [ ] 프로그램 인자가 없을 때 default path로 찾아가야 함
- [ ] timeout 확인

**Comment by flowjiyun** [comment]
아직 해결되지 않은 문제가 있어 reopen 합니다.
